[package]
name = "template"
version = "0.1.0"
authors = ["Dylan McKay <me@dylanmckay.io>"]

[dependencies]
error-chain = "0.10"
regex = "0.2"

[lib]
name = "template"
path = "src/lib.rs"

[[bin]]
name = "dump"
path = "tools/dump.rs"
